In [1]:
import pandas as pd
import numpy as np

In [12]:
df = pd.read_csv('/mnt/c/Users/CINPC0075/Desktop/Repo-KCIN3D-reconstruction/Demo1_233D1CSZ_横断図25.csv',index_col=0)
df.head()

,Name,Author,Closed,Color,Comments,Drawing Revision Number,EdgeStyleId,FaceStyleId,File Accessed,File Created,...,TextDefinedSize,Height,Obliquing,Position X,Position Y,Position Z,Rotation,Style,Value,Width Factor
Count,,,,,,,,,,,,,,,,,,,,,
1,Arc,NaN,NaN,white,NaN,NaN,0,0,05/03/2021 08:58,05/03/2021 08:58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arc,NaN,NaN,white,NaN,NaN,0,0,05/03/2021 08:58,05/03/2021 08:58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arc,NaN,NaN,white,NaN,NaN,0,0,05/03/2021 08:58,05/03/2021 08:58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arc,NaN,NaN,white,NaN,NaN,0,0,05/03/2021 08:58,05/03/2021 08:58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arc,NaN,NaN,white,NaN,NaN,0,0,05/03/2021 08:58,05/03/2021 08:58,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.info()
print('----------------------------------',
     "---------------------------------------",
     '-------------------------------------')
df.shape

<class 'pandas.core.frame.DataFrame'>
Int64Index: 983 entries, 1 to 9
Data columns (total 72 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     983 non-null    object
 1   Author                   0 non-null      float64
 2   Closed                   47 non-null     object
 3   Color                    983 non-null    object
 4   Comments                 0 non-null      float64
 5   Drawing Revision Number  0 non-null      float64
 6   EdgeStyleId              983 non-null    int64
 7   FaceStyleId              983 non-null    int64
 8   File Accessed            983 non-null    object
 9   File Created             983 non-null    object
 10  File Last Saved By       983 non-null    object
 11  File Location            983 non-null    object
 12  File Modified            983 non-null    object
 13  File Name                983 non-null    object
 14  File Size                983 non-null    int64
 15  Fit Smooth               47 non-null     object
 16  Hyperlink                0 non-null      float64
 17  Hyperlink Base           0 non-null      float64
 18  Keywords                 0 non-null      float64
 19  Layer                    983 non-null    object
 20  Length                   878 non-null    float64
 21  Linetype                 983 non-null    object
 22  Linetype Scale           983 non-null    int64
 23  Lineweight               983 non-null    object
 24  Material                 886 non-null    object
 25  Plot Style               983 non-null    object
 26  Subject                  0 non-null      float64
 27  Title                    0 non-null      float64
 28  Total Editing Time       983 non-null    int64
 29  VisualStyleId            983 non-null    int64
 30  Area                     420 non-null    float64
 31  Center X                 418 non-null    float64
 32  Center Y                 418 non-null    float64
 33  Center Z                 418 non-null    float64
 34  Radius                   418 non-null    float64
 35  Start Angle              410 non-null    float64
 36  Thickness                932 non-null    float64
 37  Total Angle              410 non-null    float64
 38  Circumference            8 non-null      float64
 39  Diameter                 8 non-null      float64
 40  Angle                    2 non-null      float64
 41  Associative              2 non-null      object
 42  BackgroundColor          0 non-null      float64
 43  Double                   2 non-null      object
 44  Origin X                 2 non-null      float64
 45  Origin Y                 2 non-null      float64
 46  Pattern Name             2 non-null      object
 47  Scale                    2 non-null      float64
 48  Spacing                  2 non-null      float64
 49  Type                     2 non-null      object
 50  Angle1                   421 non-null    float64
 51  Delta X                  421 non-null    float64
 52  Delta Y                  421 non-null    float64
 53  Delta Z                  421 non-null    float64
 54  End X                    421 non-null    float64
 55  End Y                    421 non-null    float64
 56  End Z                    421 non-null    float64
 57  Start X                  421 non-null    float64
 58  Start Y                  421 non-null    float64
 59  Start Z                  421 non-null    float64
 60  Dim Style                2 non-null      object
 61  DynamicDimension         2 non-null      object
 62  TextDefinedSize          2 non-null      object
 63  Height                   95 non-null     object
 64  Obliquing                93 non-null     float64
 65  Position X               93 non-null     float64
 66  Position Y               93 non-null     float64
 67  Position Z               93 non-null     float64
 68  Rotation                 93 non-null     float64
 69  Style                    93 non-null     object
 70  Value                    93 non-null     object
 71  Width Factor             93 non-null     float64
dtypes: float64(41), int64(6), object(25)
memory usage: 560.6+ KB
---------------------------------- --------------------------------------- -------------------------------------

(983, 72)

In [14]:
to_drop = ['Author','Closed', 'Comments', 'Drawing Revision Number', 'EdgeStyleId', 'FaceStyleId', 'File Accessed', 'File Created', 'File Last Saved By', 'File Location',
...            'File Modified','File Name', 'File Size', 'Fit Smooth', 'Hyperlink', 'Hyperlink Base', 'Keywords']

df.drop(to_drop, inplace=True, axis=1)
df.head()

,Name,Color,Layer,Length,Linetype,Linetype Scale,Lineweight,Material,Plot Style,Subject,...,TextDefinedSize,Height,Obliquing,Position X,Position Y,Position Z,Rotation,Style,Value,Width Factor
Count,,,,,,,,,,,,,,,,,,,,,
1,Arc,white,D-STR-STRB,0.0107,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arc,white,D-STR-STRB,0.0107,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arc,white,D-STR-STRB,0.0158,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arc,white,D-STR-STRB,0.0158,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Arc,white,D-STR-STRB,0.0208,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
ar = df.loc[df["Name"] == "Arc"]
ar.loc[:,["Center X"]]

       Center X
Count
1       93.6857
1       93.6857
1       93.7053
1       93.6781
1       93.8254
...         ...
1      100.9455
1      100.7579
1       62.2062
1       62.3938
1       54.7868

[410 rows x 1 columns]

In [27]:
lm = df.loc[df["Name"]== "Line"]
lm

,Name,Color,Layer,Length,Linetype,Linetype Scale,Lineweight,Material,Plot Style,Subject,...,TextDefinedSize,Height,Obliquing,Position X,Position Y,Position Z,Rotation,Style,Value,Width Factor
Count,,,,,,,,,,,,,,,,,,,,,
1,Line,white,D-STR-STRB,0.5405,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-STR-STRB,0.5405,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-STR-STRB,0.1833,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-STR-STRB,0.3500,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-STR-STRB,0.0300,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,Line,white,D-STR-DIM,2.8006,Continuous,1,0.13 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Line,red,D-STR,0.8065,Continuous,1,0.40 mm,ByLayer,Color_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Line,red,D-STR,0.8065,Continuous,1,0.40 mm,ByLayer,Color_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Line,red,D-STR,0.8065,Continuous,1,0.40 mm,ByLayer,Color_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Line,red,D-STR,0.8065,Continuous,1,0.40 mm,ByLayer,Color_1,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
llm1 = lm.loc[lm["End X"]==lm["Start X"]]
llm1

,Name,Color,Layer,Length,Linetype,Linetype Scale,Lineweight,Material,Plot Style,Subject,...,TextDefinedSize,Height,Obliquing,Position X,Position Y,Position Z,Rotation,Style,Value,Width Factor
Count,,,,,,,,,,,,,,,,,,,,,
1,Line,white,D-STR-STRB,0.0300,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-STR-STRB,0.0300,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-TTL-LINE,1.9303,Continuous,1,0.13 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-TTL-LINE,1.9303,Continuous,1,0.13 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-TTL-LINE,11.5819,Continuous,1,0.13 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1,Line,white,D-STR-STRB,0.0300,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-STR-STRB,0.1000,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-STR-STRB,0.0300,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-STR-STRB,0.0300,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,white,D-STR-STRB,0.0300,Continuous,1,0.25 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [75]:
for xi in ar["Center X"]:
    for xii in llm1["End X"]:
        if xi == xii:
            print(xi)

89.1
89.1
89.1
89.1
89.1
89.1
89.1
89.1

In [76]:
lm = df.loc[df["Name"]== "Line"]
lq = lm.loc[lm["Color"]=="red"]
lq.head

<bound method NDFrame.head of        Name Color       Layer  Length    Linetype  Linetype Scale Lineweight  \
Count
1      Line   red       D-STR  0.1562  Continuous               1    0.40 mm
1      Line   red  D-STR-STRB  0.0938  Continuous               1    0.25 mm
1      Line   red  D-STR-STRB  0.3000  Continuous               1    0.25 mm
1      Line   red       D-STR  0.5507  Continuous               1    0.40 mm
1      Line   red       D-STR  0.1380  Continuous               1    0.40 mm
...     ...   ...         ...     ...         ...             ...        ...
1      Line   red  D-STR-STRB  0.0938  Continuous               1    0.25 mm
2      Line   red       D-STR  0.8065  Continuous               1    0.40 mm
2      Line   red       D-STR  0.8065  Continuous               1    0.40 mm
2      Line   red       D-STR  0.8065  Continuous               1    0.40 mm
2      Line   red       D-STR  0.8065  Continuous               1    0.40 mm

      Material Plot Style  Subject  ...  TextDefinedSize  Height  Obliquing  \
Count                               ...
1      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN
1      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN
1      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN
1      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN
1      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN
...        ...        ...      ...  ...              ...     ...        ...
1      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN
2      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN
2      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN
2      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN
2      ByLayer    Color_1      NaN  ...              NaN     NaN        NaN

       Position X  Position Y  Position Z  Rotation  Style  Value  \
Count
1             NaN         NaN         NaN       NaN    NaN    NaN
1             NaN         NaN         NaN       NaN    NaN    NaN
1             NaN         NaN         NaN       NaN    NaN    NaN
1             NaN         NaN         NaN       NaN    NaN    NaN
1             NaN         NaN         NaN       NaN    NaN    NaN
...           ...         ...         ...       ...    ...    ...
1             NaN         NaN         NaN       NaN    NaN    NaN
2             NaN         NaN         NaN       NaN    NaN    NaN
2             NaN         NaN         NaN       NaN    NaN    NaN
2             NaN         NaN         NaN       NaN    NaN    NaN
2             NaN         NaN         NaN       NaN    NaN    NaN

       Width Factor
Count
1               NaN
1               NaN
1               NaN
1               NaN
1               NaN
...             ...
1               NaN
2               NaN
2               NaN
2               NaN
2               NaN

[210 rows x 55 columns]>

In [78]:
lq.loc[:, ["End X", "End Y", "End Z", "Start X", "Start Y", "Start Z"]]

         End X    End Y  End Z  Start X  Start Y  Start Z
Count
1      61.4517  43.5733    0.0  61.6079  43.5733      0.0
1      62.3000  43.0655    0.0  62.2062  43.0655      0.0
1      62.4500  43.0255    0.0  62.1500  43.0255      0.0
1      53.1000  50.3681    0.0  52.5500  50.3406      0.0
1      53.2000  50.2730    0.0  53.1000  50.3681      0.0
...        ...      ...    ...      ...      ...      ...
1      62.3938  98.4655    0.0  62.3000  98.4655      0.0
2      94.9225  84.7903    0.0  94.1200  84.7100      0.0
2      83.2775  84.7903    0.0  84.0800  84.7100      0.0
2      94.9225  29.3903    0.0  94.1200  29.3100      0.0
2      83.2775  29.3903    0.0  84.0800  29.3100      0.0

[210 rows x 6 columns]

In [80]:
#for 3D polyline 1
lq.sort_values(by= 'Start X', ascending=False)
lq.loc[:,["End X", "End Y", "End Z", "Start X", "Start Y", "Start Z"]]

         End X    End Y  End Z  Start X  Start Y  Start Z
Count
1      61.4517  43.5733    0.0  61.6079  43.5733      0.0
1      62.3000  43.0655    0.0  62.2062  43.0655      0.0
1      62.4500  43.0255    0.0  62.1500  43.0255      0.0
1      53.1000  50.3681    0.0  52.5500  50.3406      0.0
1      53.2000  50.2730    0.0  53.1000  50.3681      0.0
...        ...      ...    ...      ...      ...      ...
1      62.3938  98.4655    0.0  62.3000  98.4655      0.0
2      94.9225  84.7903    0.0  94.1200  84.7100      0.0
2      83.2775  84.7903    0.0  84.0800  84.7100      0.0
2      94.9225  29.3903    0.0  94.1200  29.3100      0.0
2      83.2775  29.3903    0.0  84.0800  29.3100      0.0

[210 rows x 6 columns]

In [81]:
#for 3D polyline 2
lq.sort_values(by= 'End X', ascending=False)
lq.loc[:,["End X", "End Y", "End Z", "Start X", "Start Y", "Start Z"]]

         End X    End Y  End Z  Start X  Start Y  Start Z
Count
1      61.4517  43.5733    0.0  61.6079  43.5733      0.0
1      62.3000  43.0655    0.0  62.2062  43.0655      0.0
1      62.4500  43.0255    0.0  62.1500  43.0255      0.0
1      53.1000  50.3681    0.0  52.5500  50.3406      0.0
1      53.2000  50.2730    0.0  53.1000  50.3681      0.0
...        ...      ...    ...      ...      ...      ...
1      62.3938  98.4655    0.0  62.3000  98.4655      0.0
2      94.9225  84.7903    0.0  94.1200  84.7100      0.0
2      83.2775  84.7903    0.0  84.0800  84.7100      0.0
2      94.9225  29.3903    0.0  94.1200  29.3100      0.0
2      83.2775  29.3903    0.0  84.0800  29.3100      0.0

[210 rows x 6 columns]

In [86]:
#for 3D polyline half the road right
lqhalfR = lq.loc[lq["End X"]>= 89.1]
lqhalfR.sort_values(by= 'End X', ascending=False)
lqhalfR.loc[:, ["End X", "End Y", "End Z", "Start X", "Start Y", "Start Z"]]

          End X    End Y  End Z   Start X  Start Y  Start Z
Count
1      109.9846  40.5368    0.0  105.0000  36.3830      0.0
1      104.6336  36.2015    0.0  104.6500  36.3655      0.0
1      104.6500  36.3655    0.0  104.6900  36.3655      0.0
1      104.6900  36.3355    0.0  104.6900  36.3655      0.0
1      104.5000  36.1255    0.0  104.3500  36.1255      0.0
1      104.4062  36.1655    0.0  104.5000  36.1655      0.0
1      104.6500  36.4656    0.0  104.9616  36.4812      0.0
1      105.1921  36.6733    0.0  104.9616  36.4812      0.0
1      104.6500  36.3655    0.0  105.0000  36.3830      0.0
1      104.3500  36.3655    0.0  103.5000  36.4080      0.0
1      103.8000  36.4931    0.0  104.3500  36.4656      0.0
1      103.7000  36.3980    0.0  103.8000  36.4931      0.0
1      104.6500  36.4656    0.0  104.6500  36.3655      0.0
1      104.3500  36.4656    0.0  104.3500  36.3655      0.0
1       95.1000  29.4080    0.0   94.1200  29.3100      0.0
1      105.3483  36.6733    0.0  105.1921  36.6733      0.0
1      104.6751  36.1506    0.0  104.6800  36.3255      0.0
1      104.3249  36.1506    0.0  104.3500  36.1255      0.0
1      104.6751  36.1506    0.0  104.6500  36.1255      0.0
1      104.5000  36.1655    0.0  104.5938  36.1655      0.0
1      104.3500  36.1255    0.0  104.6500  36.1255      0.0
1      104.6800  36.3255    0.0  104.6900  36.3355      0.0
1       92.3500  29.3350    0.0   89.1000  29.4000      0.0
1      103.5000  36.4080    0.0   95.1000  29.4080      0.0
1       93.6000  29.3100    0.0   92.3500  29.3350      0.0
1      101.5417  87.7312    0.0  102.0213  87.2516      0.0
1      101.5417  87.7312    0.0  101.0417  87.7312      0.0
1      110.7528  41.1770    0.0  109.9846  40.5368      0.0
1       99.2187  88.2402    0.0   98.4504  87.6000      0.0
1       98.4504  87.6000    0.0   95.1000  84.8080      0.0
1       95.1000  84.8080    0.0   94.1200  84.7100      0.0
1       93.6000  84.7100    0.0   92.3500  84.7350      0.0
1       92.3500  84.7350    0.0   89.1000  84.8000      0.0
2       94.9225  84.7903    0.0   94.1200  84.7100      0.0
2       94.9225  29.3903    0.0   94.1200  29.3100      0.0

In [87]:
#for 3D polyline half the road left
lqhalfL = lq.loc[lq["End X"]< 89.1]
lqhalfL.sort_values(by= 'End X', ascending=False)
lqhalfL.loc[:, ["End X", "End Y", "End Z", "Start X", "Start Y", "Start Z"]]

         End X    End Y  End Z  Start X  Start Y  Start Z
Count
1      61.4517  43.5733    0.0  61.6079  43.5733      0.0
1      62.3000  43.0655    0.0  62.2062  43.0655      0.0
1      62.4500  43.0255    0.0  62.1500  43.0255      0.0
1      53.1000  50.3681    0.0  52.5500  50.3406      0.0
1      53.2000  50.2730    0.0  53.1000  50.3681      0.0
...        ...      ...    ...      ...      ...      ...
1      62.1500  98.6655    0.0  62.1100  98.6655      0.0
1      62.4751  98.4506    0.0  62.4500  98.4255      0.0
1      62.3938  98.4655    0.0  62.3000  98.4655      0.0
2      83.2775  84.7903    0.0  84.0800  84.7100      0.0
2      83.2775  29.3903    0.0  84.0800  29.3100      0.0

[175 rows x 6 columns]

In [90]:
lq2DE = lq[["End X","End Y","End Z"]]
lq2DS = lq[["Start X","Start Y","Start Z"]]

In [91]:
coordinates = pd.concat([lq2DE,lq2DS], axis=1)
coordinates.reset_index(drop=True)

       End X    End Y  End Z  Start X  Start Y  Start Z
0    61.4517  43.5733    0.0  61.6079  43.5733      0.0
1    62.3000  43.0655    0.0  62.2062  43.0655      0.0
2    62.4500  43.0255    0.0  62.1500  43.0255      0.0
3    53.1000  50.3681    0.0  52.5500  50.3406      0.0
4    53.2000  50.2730    0.0  53.1000  50.3681      0.0
..       ...      ...    ...      ...      ...      ...
205  62.3938  98.4655    0.0  62.3000  98.4655      0.0
206  94.9225  84.7903    0.0  94.1200  84.7100      0.0
207  83.2775  84.7903    0.0  84.0800  84.7100      0.0
208  94.9225  29.3903    0.0  94.1200  29.3100      0.0
209  83.2775  29.3903    0.0  84.0800  29.3100      0.0

[210 rows x 6 columns]

In [16]:
coordinates.to_csv('/mnt/c/Users/CINPC0075/Desktop/Repo-KCIN3D-reconstruction/Demo1_OUT1_233D1CSZ_横断図25.csv',index=False, header=False)