In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/mnt/c/Users/CINPC0075/Desktop/Repo-KCIN3D-reconstruction/Demo1_183D1PLZ_平面図04.csv',index_col=0)
df.head()

/home/shahab/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3146: DtypeWarning: Columns (4,9,10,20,25,42,44,46,47,49,50,52,67,68) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,Name,Author,Closed,Color,Comments,Drawing Revision Number,EdgeStyleId,FaceStyleId,File Accessed,File Created,...,Position Y,Position Z,Height,Obliquing,Rotation,Style,Value,Width Factor,Unnamed: 70,Unnamed: 71
Count,,,,,,,,,,,,,,,,,,,,,
1,Line,NaN,NaN,51,51.0,51.0,NaN,NaN,0,0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,NaN,NaN,51,51.0,51.0,NaN,NaN,0,0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,NaN,NaN,51,51.0,51.0,NaN,NaN,0,0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,NaN,NaN,51,51.0,51.0,NaN,NaN,0,0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,NaN,NaN,51,51.0,51.0,NaN,NaN,0,0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.info()
print('----------------------------------',
     "---------------------------------------",
     '-------------------------------------')
df.shape

<class 'pandas.core.frame.DataFrame'>
Int64Index: 44705 entries, 1 to 160
Data columns (total 71 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Name                     44705 non-null  object
 1   Author                   0 non-null      float64
 2   Closed                   4400 non-null   object
 3   Color                    44705 non-null  object
 4   Comments                 39306 non-null  float64
 5   Drawing Revision Number  39306 non-null  float64
 6   EdgeStyleId              5399 non-null   float64
 7   FaceStyleId              5399 non-null   float64
 8   File Accessed            44705 non-null  object
 9   File Created             44705 non-null  object
 10  File Last Saved By       44705 non-null  object
 11  File Location            44705 non-null  object
 12  File Modified            44705 non-null  object
 13  File Name                44705 non-null  object
 14  File Size                44705 non-null  object
 15  Fit Smooth               39914 non-null  object
 16  Hyperlink                39306 non-null  float64
 17  Hyperlink Base           3792 non-null   object
 18  Keywords                 0 non-null      float64
 19  Layer                    5399 non-null   object
 20  Length                   4117 non-null   float64
 21  Linetype                 44705 non-null  object
 22  Linetype Scale           40646 non-null  float64
 23  Lineweight               44705 non-null  object
 24  Material                 43848 non-null  object
 25  Plot Style               44705 non-null  object
 26  Subject                  37321 non-null  object
 27  Title                    39306 non-null  object
 28  Total Editing Time       5399 non-null   float64
 29  VisualStyleId            5399 non-null   float64
 30  Area                     40597 non-null  float64
 31  Center X                 40503 non-null  float64
 32  Center Y                 4764 non-null   float64
 33  Center Z                 4566 non-null   float64
 34  Radius                   4566 non-null   float64
 35  Start Angle              4141 non-null   float64
 36  Thickness                8065 non-null   float64
 37  Total Angle              2067 non-null   float64
 38  Circumference            35741 non-null  float64
 39  Diameter                 1720 non-null   float64
 40  Angle1                   2168 non-null   float64
 41  Associative              2168 non-null   object
 42  BackgroundColor          198 non-null    float64
 43  Double                   292 non-null    object
 44  Origin X                 94 non-null     float64
 45  Origin Y                 292 non-null    object
 46  Pattern Name             292 non-null    object
 47  Scale                    292 non-null    float64
 48  Spacing                  292 non-null    object
 49  Type                     292 non-null    object
 50  Angle                    2935 non-null   float64
 51  Delta X                  2935 non-null   object
 52  Delta Y                  32897 non-null  float64
 53  Delta Z                  32897 non-null  float64
 54  End X                    32897 non-null  float64
 55  End Y                    32897 non-null  float64
 56  End Z                    32897 non-null  float64
 57  Start X                  32897 non-null  float64
 58  Start Y                  32897 non-null  float64
 59  Start Z                  32897 non-null  float64
 60  Position X               30922 non-null  float64
 61  Position Y               30922 non-null  float64
 62  Position Z               2549 non-null   float64
 63  Height                   2507 non-null   float64
 64  Obliquing                2507 non-null   float64
 65  Rotation                 2507 non-null   float64
 66  Style                    2507 non-null   object
 67  Value                    2507 non-null   object
 68  Width Factor             2507 non-null   object
 69  Unnamed: 70              1788 non-null   object
 70  Unnamed: 71              1787 non-null   float64
dtypes: float64(41), object(30)
memory usage: 24.6+ MB
---------------------------------- --------------------------------------- -------------------------------------

(44705, 71)

In [4]:
to_drop = ['Author','Closed', 'Comments', 'Drawing Revision Number', 'EdgeStyleId', 'FaceStyleId', 'File Accessed', 'File Created', 'File Last Saved By', 'File Location',
...            'File Modified','File Name', 'File Size', 'Fit Smooth', 'Hyperlink', 'Hyperlink Base', 'Keywords']
df.drop(to_drop, inplace=True, axis=1)
df.head()

,Name,Color,Layer,Length,Linetype,Linetype Scale,Lineweight,Material,Plot Style,Subject,...,Position Y,Position Z,Height,Obliquing,Rotation,Style,Value,Width Factor,Unnamed: 70,Unnamed: 71
Count,,,,,,,,,,,,,,,,,,,,,
1,Line,51,NaN,NaN,S-BGD-EXST,0.2311,Continuous,1,0.13 mm,ByLayer,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,51,NaN,NaN,S-BGD-EXST,0.2549,Continuous,1,0.13 mm,ByLayer,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,51,NaN,NaN,S-BGD-EXST,0.1370,Continuous,1,0.13 mm,ByLayer,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,51,NaN,NaN,S-BGD-EXST,0.1567,Continuous,1,0.13 mm,ByLayer,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Line,51,NaN,NaN,S-BGD-EXST,0.1567,Continuous,1,0.13 mm,ByLayer,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.set_index("Value",inplace= True)
df

,Name,Color,Layer,Length,Linetype,Linetype Scale,Lineweight,Material,Plot Style,Subject,...,Position X,Position Y,Position Z,Height,Obliquing,Rotation,Style,Width Factor,Unnamed: 70,Unnamed: 71
Value,,,,,,,,,,,,,,,,,,,,,
NaN,Line,51,NaN,NaN,S-BGD-EXST,0.2311,Continuous,1,0.13 mm,ByLayer,...,396.7315,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Line,51,NaN,NaN,S-BGD-EXST,0.2549,Continuous,1,0.13 mm,ByLayer,...,396.5130,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Line,51,NaN,NaN,S-BGD-EXST,0.1370,Continuous,1,0.13 mm,ByLayer,...,395.4753,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Line,51,NaN,NaN,S-BGD-EXST,0.1567,Continuous,1,0.13 mm,ByLayer,...,395.6385,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Line,51,NaN,NaN,S-BGD-EXST,0.1567,Continuous,1,0.13 mm,ByLayer,...,395.5307,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,Hatch,yellow,S-BMK,NaN,USER_12,1.0000,0.13 mm,NaN,Color_2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3D Polyline,51,NaN,NaN,S-SUV,4.1761,Continuous,1,0.20 mm,ByLayer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3D Polyline,51,NaN,NaN,S-SUV,4.1761,Continuous,1,0.20 mm,ByLayer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3D Polyline,51,NaN,NaN,S-SUV,5.0000,Continuous,1,0.20 mm,ByLayer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,3D Polyline,51,NaN,NaN,S-SUV,4.1761,Continuous,1,0.20 mm,ByLayer,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
dff = df.loc[["NO.270", "NO.271","NO.272","NO.273","NO.274","NO.275","NO.276","NO.277","NO.278","NO.279"], ["Position X", "Position Y", "Position Z"]]
dff.sort_values("Position X", inplace=True, ascending=True)
dff

        Position X  Position Y  Position Z
Value
NO.270     47.0625    266.1909         0.0
NO.271     65.6793    273.4993         0.0
NO.272     83.0477    279.8883         0.0
NO.273    106.1021    288.5276         0.0
NO.274    122.0032    294.1664         0.0
NO.275    141.4029    301.1899         0.0
NO.276    160.5373    307.0066         0.0
NO.277    179.6717    312.8234         0.0
NO.278    198.9520    318.1393         0.0
NO.279    216.0298    329.8597         0.0

In [7]:
df1 = df.loc[df["Name"] == 'Circle']
df2 = df1.loc[df1["Radius"] == 2.5]
df2

,Name,Color,Layer,Length,Linetype,Linetype Scale,Lineweight,Material,Plot Style,Subject,...,Position X,Position Y,Position Z,Height,Obliquing,Rotation,Style,Width Factor,Unnamed: 70,Unnamed: 71
Value,,,,,,,,,,,,,,,,,,,,,
NaN,Circle,white,D-BMK,NaN,USER_12,1.0,0.18 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Circle,white,D-BMK,NaN,USER_12,1.0,0.18 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Circle,white,D-BMK,NaN,USER_12,1.0,0.18 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Circle,white,D-BMK,NaN,USER_12,1.0,0.18 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Circle,white,D-BMK-HTXT,NaN,USER_12,1.0,0.18 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Circle,white,D-BMK,NaN,USER_12,1.0,0.18 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Circle,white,D-BMK,NaN,USER_12,1.0,0.18 mm,ByLayer,Color_7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df22 = df2.loc[df2["Name"] == "Circle", ["Center X", "Center Y", "Center Z"]]
df22.sort_values("Center X", inplace=True, ascending=True)
df22

       Center X  Center Y  Center Z
Value
NaN     55.0058  248.6300       0.0
NaN    148.9235  282.9196       0.0
NaN    245.2960  309.4909       0.0
NaN    343.6120  327.5921       0.0
NaN    443.1287  337.0865       0.0
NaN    543.0938  337.9023       0.0
NaN    642.7521  330.0334       0.0

# Measuring the shortest distance between the Circles-centers and the Tags, 
## for each pair (Circle,tag), we choose the shortest distance.

In [80]:
rrx = df22["Center X"]
rry = df22["Center Y"]
rrrx = dff["Position X"]
rrry = dff["Position Y"]
import math
fel=[]
kk = dff.index[k]
for i, j in zip(rrrx,rrry):
    for m, n in zip(rrx,rry):
        f= math.sqrt((j-n)**2 + (i-m)**2)
        fel.append([i,j,m,n,f])
fel

[[47.0625, 266.1909, 55.0058, 248.63, 19.273848180890088],
 [47.0625, 266.1909, 148.9235, 282.9196, 103.2255429856874],
 [47.0625, 266.1909, 245.296, 309.4909, 202.90739395657812],
 [47.0625, 266.1909, 343.61199999999997, 327.5921, 302.8394183584594],
 [47.0625, 266.1909, 443.1287, 337.0865, 402.3613063924015],
 [47.0625, 266.1909, 543.0938, 337.9023, 501.18816373658507],
 [47.0625, 266.1909, 642.7521, 330.0334, 599.1009634063444],
 [65.6793, 273.4993, 55.0058, 248.63, 27.06299474817967],
 [65.6793, 273.4993, 148.9235, 282.9196, 83.77552677082967],
 [65.6793, 273.4993, 245.296, 309.4909, 183.18721076933835],
 [65.6793, 273.4993, 343.61199999999997, 327.5921, 283.1476942182825],
 [65.6793, 273.4993, 443.1287, 337.0865, 382.76805191159826],
 [65.6793, 273.4993, 543.0938, 337.9023, 481.73888281853476],
 [65.6793, 273.4993, 642.7521, 330.0334, 579.8354257568694],
 [83.0477, 279.8883, 55.0058, 248.63, 41.993207480496196],
 [83.0477, 279.8883, 148.9235, 282.9196, 65.94550633159167],
 [83.0477, 279.8883, 245.296, 309.4909, 164.92672548635042],
 [83.0477, 279.8883, 343.61199999999997, 327.5921, 264.89508672100726],
 [83.0477, 279.8883, 443.1287, 337.0865, 364.5956124862722],
 [83.0477, 279.8883, 543.0938, 337.9023, 463.6895926384481],
 [83.0477, 279.8883, 642.7521, 330.0334, 561.9462131141823],
 [106.1021, 288.5276, 55.0058, 248.63, 64.82785172632208],
 [106.1021, 288.5276, 148.9235, 282.9196, 43.187057806245605],
 [106.1021, 288.5276, 245.296, 309.4909, 140.7636378618427],
 [106.1021, 288.5276, 343.61199999999997, 327.5921, 240.70103397837738],
 [106.1021, 288.5276, 443.1287, 337.0865, 340.50682207082133],
 [106.1021, 288.5276, 543.0938, 337.9023, 439.7722215749649],
 [106.1021, 288.5276, 642.7521, 330.0334, 538.2526859511619],
 [122.0032, 294.1664, 55.0058, 248.63, 81.00750170027466],
 [122.0032, 294.1664, 148.9235, 282.9196, 29.175213149692656],
 [122.0032, 294.1664, 245.296, 309.4909, 124.24151814948976],
 [122.0032, 294.1664, 343.61199999999997, 327.5921, 224.11545608888733],
 [122.0032, 294.1664, 443.1287, 337.0865, 323.9810515049607],
 [122.0032, 294.1664, 543.0938, 337.9023, 423.3557869654907],
 [122.0032, 294.1664, 642.7521, 330.0334, 521.9826228335672],
 [141.4029, 301.1899, 55.0058, 248.63, 101.12864073258378],
 [141.4029, 301.1899, 148.9235, 282.9196, 19.75761337940392],
 [141.4029, 301.1899, 245.296, 309.4909, 104.22419502500368],
 [141.4029, 301.1899, 343.61199999999997, 327.5921, 203.9254674817493],
 [141.4029, 301.1899, 443.1287, 337.0865, 303.8536231102074],
 [141.4029, 301.1899, 543.0938, 337.9023, 403.36506970307926],
 [141.4029, 301.1899, 642.7521, 330.0334, 502.1782231766826],
 [160.5373, 307.0066, 55.0058, 248.63, 120.60151292504584],
 [160.5373, 307.0066, 148.9235, 282.9196, 26.740679113291034],
 [160.5373, 307.0066, 245.296, 309.4909, 84.79509993024362],
 [160.5373, 307.0066, 343.61199999999997, 327.5921, 184.22841417745525],
 [160.5373, 307.0066, 443.1287, 337.0865, 284.18778956522743],
 [160.5373, 307.0066, 543.0938, 337.9023, 383.80205832009295],
 [160.5373, 307.0066, 642.7521, 330.0334, 482.76427669959185],
 [179.6717, 312.8234, 55.0058, 248.63, 140.22260597482133],
 [179.6717, 312.8234, 148.9235, 282.9196, 42.89159658581153],
 [179.6717, 312.8234, 245.296, 309.4909, 65.70886018445306],
 [179.6717, 312.8234, 343.61199999999997, 327.5921, 164.60418118559443],
 [179.6717, 312.8234, 443.1287, 337.0865, 264.5718973561062],
 [179.6717, 312.8234, 543.0938, 337.9023, 364.28639007464994],
 [179.6717, 312.8234, 642.7521, 330.0334, 463.4000873588179],
 [198.952, 318.1393, 55.0058, 248.63, 159.85009002477915],
 [198.952, 318.1393, 148.9235, 282.9196, 61.18233470814921],
 [198.952, 318.1393, 245.296, 309.4909, 47.14404690477897],
 [198.952, 318.1393, 343.61199999999997, 327.5921, 144.9685173678754],
 [198.952, 318.1393, 443.1287, 337.0865, 244.91071273166062],
 [198.952, 318.1393, 543.0938, 337.9023, 344.7087969232001],
 [198.952, 318.1393, 642.7521, 330.0334, 443.9594557781375],
 [216.0298, 329.8597, 55.0058, 248.63, 180.35241262065222],
 [216.0298, 329.8597, 148.9235, 282.9196, 81.89400764219565],
 [216.0298, 329.8597, 245.296, 309.4909, 35.65667505362774],
 [216.0298, 329.8597, 343.61199999999997, 327.5921, 127.602350160959],
 [216.0298, 329.8597, 443.1287, 337.0865, 227.2138574547116],
 [216.0298, 329.8597, 543.0938, 337.9023, 327.16287000630126],
 [216.0298, 329.8597, 642.7521, 330.0334, 426.7223353528381]]

In [96]:
fol = pd.DataFrame(fel, columns = list('TAGds'))
fol270 = fol.loc[fol['T'] == 47.0625]
fol270
maxClm270 = fol270['s'].min()
print(maxClm270)
fi = fol.drop_duplicates('T', keep='first')
fii = fol.groupby('T', group_keys=False).apply(lambda x: x.loc[x.s.idxmin()])
print(fi,fii)

19.273848180890088
           T         A        G       d           s
0    47.0625  266.1909  55.0058  248.63   19.273848
7    65.6793  273.4993  55.0058  248.63   27.062995
14   83.0477  279.8883  55.0058  248.63   41.993207
21  106.1021  288.5276  55.0058  248.63   64.827852
28  122.0032  294.1664  55.0058  248.63   81.007502
35  141.4029  301.1899  55.0058  248.63  101.128641
42  160.5373  307.0066  55.0058  248.63  120.601513
49  179.6717  312.8234  55.0058  248.63  140.222606
56  198.9520  318.1393  55.0058  248.63  159.850090
63  216.0298  329.8597  55.0058  248.63  180.352413                  T         A         G         d          s
T
47.0625    47.0625  266.1909   55.0058  248.6300  19.273848
65.6793    65.6793  273.4993   55.0058  248.6300  27.062995
83.0477    83.0477  279.8883   55.0058  248.6300  41.993207
106.1021  106.1021  288.5276  148.9235  282.9196  43.187058
122.0032  122.0032  294.1664  148.9235  282.9196  29.175213
141.4029  141.4029  301.1899  148.9235  282.9196  19.757613
160.5373  160.5373  307.0066  148.9235  282.9196  26.740679
179.6717  179.6717  312.8234  148.9235  282.9196  42.891597
198.9520  198.9520  318.1393  245.2960  309.4909  47.144047
216.0298  216.0298  329.8597  245.2960  309.4909  35.656675

In [97]:
fi.to_csv('/mnt/c/Users/CINPC0075/Desktop/Repo-KCIN3D-reconstruction/Demo1_OUT1_183D1PLZ_平面図04.csv',index=False, header=False)

In [1]:
# Python Program implement
# the above approach

# Function to generate determinant
def det(d):
	Sum = d[0][0] * ((d[1][1] * d[2][2])
					- (d[2][1] * d[1][2]))
	Sum -= d[0][1] * ((d[1][0] * d[2][2])
					- (d[1][2] * d[2][0]))
	Sum += d[0][2] * ((d[0][1] * d[1][2])
					- (d[0][2] * d[1][1]))

	# Return the sum
	return Sum

# Driver Code
if __name__ == '__main__':

	# Position vector of first line
	x1, y1, z1 = -3, 1, 5

	# Direction ratios of line to
	# which first line is parallel
	a1, b1, c1 = -3, 1, 5

	# Position vectors of second line
	x2, y2, z2 = -1, 2, 5

	# Direction ratios of line to
	# which second line is parallel
	a2, b2, c2 = -1, 2, 5

	# Determinant to check coplanarity
	det_list = [[x2-x1, y2-y1, z2-z1],
				[a1, b1, c1], [a2, b2, c2]]

	# If determinant is zero
	if(det(det_list) == 0):
		print("Lines are coplanar")

	# Otherwise
	else:
		print("Lines are non coplanar")

Lines are coplanar